### ISSUE TITLE
add new query params and documentation for get projects API

### ISSUE THREAD

**Issue by ArtyomHov** [renderforest/renderforest-sdk-php#127]
There are new query parameters in get projects API endpoint, which should be implemented in SDK.
* optional query parameter `includeApiProjects`:boolean (default `false`)
* optional query parameter `order`:string (default `DESC`), possible values: `ASC` and `DESC`
* optional query parameter `orderBy`:string (default `order`), possible values: `order` and `date`
in /projects/getProjects

Update:
Also add search param:
* optional query parameter `search`:string (max characters: 70)

**Comment by narekhovhannisyan** [comment]
👅

**Comment by narekhovhannisyan** [comment]
optional query parameter `search`:string (max characters: 70), I don't remember anything like this in your code

**Comment by ArtyomHov** [comment]
Leave it out. I will update it in documentation later on.

**Comment by narekhovhannisyan** [comment]
you've stayed alive 😄
