### ISSUE TITLE
Error in Recursive function name

### ISSUE THREAD

**Issue by molmi** [renderforest/renderforest-sdk-php#86]
In the file /src/lib/http/Http.php, line 61 and 66, the function is not the same (it generate error), maybe you should rename it recursiveUnset in line 66

**Comment by narekhovhannisyan** [comment]
You're right @molmi, thanks, it will be fixed soon.

**Comment by narekhovhannisyan** [comment]
ec9b9c2809500c17f581686975e894171e91a227
fixed :)
